### ISSUE TITLE
Node saas environment binding with Docker

### ISSUE THREAD

**Issue by M2Key** [MarkPieszak/aspnetcore-angular2-universal#218]
I'm trying to put the application in a docker container. The problem is that when I ran npm install, I was on Windows 64-bit with Node.js 7.x, but my docker container container is on Linux 64-bit with Node.js 7.x.

So when I run my application in the Docker container through Visual Studio 2017, I have this error : 

```
`Module build failed: Error: Missing binding /app/node_modules/node-sass/vendor/linux-x64-51/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 7.x
```

Here's my DockerFile

```
FROM microsoft/aspnetcore:1.1.1

RUN apt-get update
RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash
RUN apt-get install nodejs
RUN node -v
RUN npm -v
RUN npm install
RUN npm rebuild node-sass --force


ARG source
WORKDIR /app
EXPOSE 5000
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "platform.dll"]
```

Here's my docker-compose.ci.build.yml file

```
version: '2'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./platform.sln && dotnet publish ./platform.sln -c Release -o ./obj/Docker/publish" 
```
I tries on both file to add the command `npm rebuild node-sass --force` but did not change anything.

Any advice?
